pipeline {
    agent any
    stages {     
        stage('Build') {
            agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
                    }
             }
            
            steps {
                sh 'mvn -B -DskipTests clean package'
                archiveArtifacts artifacts: 'target/*.jar' , fingerprint: true , followSymlinks: false , onlyIfSuccessful: true
            }
        }
		stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
             
        }
        stage('Docker build') {
            steps {
                sh 'docker build -t meghags17/simple_java .'
                sh 'docker run -it  -d meghags17/simple_java'
            }
        }
        
    }
}
